name: CI

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install ruff mypy pytest jsonschema pre-commit

      - name: Lint (ruff)
        run: ruff check anyon_condense

      - name: Typecheck (mypy)
        run: mypy anyon_condense

      - name: Tests (pytest)
        run: pytest -q
